version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    image: prod_nginx
    container_name: prod_nginx
    volumes:
      - ./dist:/usr/share/nginx/html/
      - ./compose/production/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/app
    ports:
      - "80:80"
    networks:
      - asura-web_service
    command: [nginx, '-g', 'daemon off;']

networks:
  asura-web_service:
    external: true