export const RECORD_USERINFO = 'RECORD_USERINFO';

export const RESET_STORE = 'RESET_STORE';

export const SEND_RESET_PASSWORD_EMAIL = 'SEND_RESET_PASSWORD_EMAIL';

export const RESET_PASSWORD = 'RESET_PASSWORD';

export const RECORD_SERVICES = 'RECORD_SERVICES';

export const UPDATE_SERVICE = 'UPDATE_SERVICE';

export const RECORD_ENVIRONMENTS = 'RECORD_ENVIRONMENTS';

export const RECORD_ENVIRONMENT = 'RECORD_ENVIRONMENT';

export const DELETE_ENVIRONMENT = 'DELETE_ENVIRONMENT';

export const UPDATE_ENVIRONMENT = 'UPDATE_ENVIRONMENT';

export const ADD_ENVIRONMENT = 'ADD_ENVIRONMENT';

export const RECORD_TESTS = 'RECORD_TESTS';

export const DELETE_TEST = 'DELETE_TEST';

export const UPDATA_TEST = 'UPDATA_TEST';

export const CREATE_TEST = 'CREATE_TEST';

export const RECORD_STEPS = 'RECORD_STEPS';

export const UPDATE_STEPS = 'UPDATE_STEPS';

export const DELETE_SETUP_STEP = 'DELETE_SETUP_STEP';

export const CREATE_SETUP_STEP = 'CREATE_SETUP_SETP';

export const RECORD_SETUPS = 'RECORD_SETUPS';

export const CREATE_SETUP = 'CREATE_SETUP';

export const DELETE_SETUP = 'DELETE_SETUP';

export const UPDATE_SETUP = 'UPDATE_SETUP';

export const RECORD_TEARDOWNS = 'RECORD_TEARDOWNS';

export const CREATE_TEARDOWN = 'CREATE_TEARDOWN';

export const DELETE_TEARDOWN = 'DELETE_TEARDOWN';

export const UPDATE_TEARDOWN = 'UPDATE_TEARDOWN';

export const CREATE_TEARDOWN_STEP = 'CREATE_TEARDOWN_STEP';

export const DELETE_TEARDOWN_STEP = 'DELETE_TEARDOWN_STEP';

export const RECORD_ASSERTIONS = 'RECORD_ASSERTIONS';

export const CREATE_ASSERTION = 'CREATE_ASSERTION';

export const DELETE_ASSERTION = 'DELETE_ASSERTION';

export const UPDATE_ASSERTION = 'UPDATE_ASSERTION';

export const RECORD_RESULTS = 'RECORD_RESULTS';

export const CREATE_RESULT = 'CREATE_RESULT';

export const RECORD_SUITES = 'RECORD_SUITES';

export const CREATE_SUITE = 'CREATE_SUITE';

export const RECORD_NEW_SERVICE = 'RECORD_NEW_SERVICE';

export const RECORD_SCHEDULES = 'RECORD_SCHEDULES';

export const CREATE_SCHEDULE = 'CREATE_SCHEDULE';

export const DELETE_SCHEDULE = 'DELETE_SCHEDULE';

export const UPDATE_SCHEDULE = 'UPDATE_SCHEDULE';

export const ADD_TEST_TO_SCHEDULE = 'ADD_TEST_TO_SCHEDULE';

export const DELETE_TEST_FROM_SCHEDULE = 'DELETE_TEST_FROM_SCHEDULE';

export const RECORD_HOOKS = 'RECORD_HOOKS';

export const CREATE_HOOK = 'CREATE_HOOK';

export const DELETE_HOOK = 'DELETE_HOOK';

export const UPDATE_HOOK = 'UPDATE_HOOK';

export const ADD_TEST_TO_HOOK = 'ADD_TEST_TO_HOOK';

export const DELETE_TEST_FROM_HOOK = 'DELETE_TEST_FROM_HOOK';
